before_script:
  - psql -c 'CREATE DATABASE Prototype_test;' -U postgres

script:
  - bundle exec rake

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app:
    devmaster: daily-dive-staging
